# Generated by Django 4.2.3 on 2023-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUSER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USUNAME', models.TextField(max_length=255)),
                ('USUPASS', models.TextField(max_length=255)),
            ],
        ),
    ]
