# Generated by Django 4.2.3 on 2023-08-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuser',
            old_name='USUNAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tuser',
            old_name='USUPASS',
            new_name='password',
        ),
    ]
